## Demonstrate module's work

In [7]:
import numpy as np
from projection import get_projections

np.set_printoptions(precision=2)

In [15]:
P = np.array([0,0,0])
N = np.array([0,0,1])
# generate normally distributed points (mu=0, sigma=2)
points_to_project = 2*np.random.randn(10,3)

projections = get_projections(P, N, points_to_project)

print('Initial points: \n', points_to_project)
print('Projected points: \n', projections)

Initial points: 
 [[ 1.12  1.   -1.21]
 [-1.   -1.48 -3.01]
 [-2.68  1.85  1.27]
 [-0.32 -1.2  -1.47]
 [ 0.96  0.86  2.31]
 [-1.28  1.14  0.43]
 [ 0.05 -1.1   0.95]
 [-1.44  1.17 -3.06]
 [ 1.83 -1.19  1.06]
 [-0.28  1.64 -2.51]]
Projected points: 
 [[ 1.12  1.    0.  ]
 [-1.   -1.48  0.  ]
 [-2.68  1.85  0.  ]
 [-0.32 -1.2   0.  ]
 [ 0.96  0.86  0.  ]
 [-1.28  1.14  0.  ]
 [ 0.05 -1.1   0.  ]
 [-1.44  1.17  0.  ]
 [ 1.83 -1.19  0.  ]
 [-0.28  1.64  0.  ]]


## Visualize

In [16]:
import numpy as np
from plotly.offline import init_notebook_mode, iplot
import plotly.graph_objs as go

init_notebook_mode(connected=True)

In [18]:
trace_init_points = go.Scatter3d(
    x=points_to_project[:,0],
    y=points_to_project[:,1],
    z=points_to_project[:,2],
    mode='markers',
    marker=dict(
        size=3,
        opacity=0.8
    )
)

trace_projections = go.Scatter3d(
     x=projections[:,0],
     y=projections[:,1],
     z=projections[:,2],
     mode='markers',
     marker=dict(
         size=3,
         opacity=0.8,
         color='green'
     )
)

trace_plane = go.Mesh3d(
    x = projections[:,0],
    y = projections[:,1],
    z = projections[:,2],
    color = 'green',
    opacity= 0.3,
)

data = [trace_init_points, trace_projections, trace_plane]
fig = go.Figure(data=data)
iplot(fig)