## Demonstrate module's work

In [1]:
import numpy as np
from projection import get_projections_to_plane, get_distances_to_plane

np.set_printoptions(precision=2)

In [4]:
P = np.array([0,0,0])
N = np.array([0,0,1])
# generate 10 normally distributed 3D points (mu=0, sigma=2)
points = 2*np.random.randn(10,3)

projections = get_projections_to_plane(P, N, points)
distances = get_distances_to_plane(P, N, points)

print('Initial points: \n', points)
print()
print('Distance to plane: \n', distances)
print()
print('Projections: \n', projections)

Initial points: 
 [[-4.65  1.46  1.69]
 [ 2.08  0.81 -0.2 ]
 [-1.16 -3.15 -2.68]
 [-0.34  0.45  1.41]
 [-1.63 -0.07 -0.93]
 [ 0.54 -0.37  0.73]
 [-2.34  1.94 -0.43]
 [-1.14 -1.96 -0.21]
 [ 2.47  2.56 -1.9 ]
 [-0.15 -2.34 -2.37]]

Distance to plane: 
 [1.69 0.2  2.68 1.41 0.93 0.73 0.43 0.21 1.9  2.37]

Projections: 
 [[-4.65  1.46  0.  ]
 [ 2.08  0.81  0.  ]
 [-1.16 -3.15  0.  ]
 [-0.34  0.45  0.  ]
 [-1.63 -0.07  0.  ]
 [ 0.54 -0.37  0.  ]
 [-2.34  1.94  0.  ]
 [-1.14 -1.96  0.  ]
 [ 2.47  2.56  0.  ]
 [-0.15 -2.34  0.  ]]


## Visualize

In [5]:
import numpy as np
from plotly.offline import init_notebook_mode, iplot
import plotly.graph_objs as go

init_notebook_mode(connected=True)

In [6]:
trace_init_points = go.Scatter3d(
    x=points[:,0],
    y=points[:,1],
    z=points[:,2],
    mode='markers',
    marker=dict(
        size=3,
        opacity=0.8
    )
)

trace_projections = go.Scatter3d(
     x=projections[:,0],
     y=projections[:,1],
     z=projections[:,2],
     mode='markers',
     marker=dict(
         size=3,
         opacity=0.8,
         color='green'
     )
)

trace_plane = go.Mesh3d(
    x = projections[:,0],
    y = projections[:,1],
    z = projections[:,2],
    color = 'green',
    opacity= 0.3,
)

data = [trace_init_points, trace_projections, trace_plane]
fig = go.Figure(data=data)
iplot(fig)